name: Mirror official site

on:
  schedule:
    - cron:  '14 1 * * *'
  workflow_dispatch: {}

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install OS dependencies
      run: sudo apt-get install jq moreutils
    - name: Install ruby dependencies
      run: bundle install
    - name: Mirror official site
      run: bash bin/mirror.sh
    - name: Commit and push if changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add mirror
        timestamp=$(date -u)
        git commit -m "Update mirror: ${timestamp}" || exit 0
        git push
